logsBucket: 'gs://prod-nehemiebarkia-fix-builds'

options:
  logging: GCS_ONLY

substitutions:
  _TAG: "v1.0.0"

steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "hello world, tag : $TAG"'
    env:
      - 'TAG=${_TAG}'
