logsBucket: 'gs://prod-nehemiebarkia-fix-builds'

substitutions:
  _DOCKERHUB_USER: 'elticketo'
options:
  logging: GCS_ONLY

steps:
  # Debug
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'ls -lisah ./']

  # Login   
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$DOCKERHUB_USERNAME --password=$$DOCKERHUB_PASSWORD']
    secretEnv: ['DOCKERHUB_USERNAME', 'DOCKERHUB_PASSWORD']

  # Build et push de l'api
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'docker.io/${_DOCKERHUB_USER}/elticketo-api:${TAG_NAME}'
    - './BackEnd'
    id: 'build-api'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'docker.io/${_DOCKERHUB_USER}/elticketo-api:${_TAG_NAME}'

  # Build et push du frontend app
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'docker.io/${_DOCKERHUB_USER}/elticketo-app:${_TAG_NAME}'
      - './FrontEnd'
    id: 'build-app'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'docker.io/${_DOCKERHUB_USER}/elticketo-app:${_TAG_NAME}'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DOCKERHUB_USERNAME/versions/latest
      env: 'DOCKERHUB_USERNAME'
    - versionName: projects/$PROJECT_ID/secrets/DOCKERHUB_PASSWORD/versions/latest
      env: 'DOCKERHUB_PASSWORD'
