logsBucket: 'gs://prod-nehemiebarkia-fix-builds'

options:
  logging: GCS_ONLY

steps:
  # Install Ansible
  - name: 'ansible/ansible:latest'
    entrypoint: 'ansible-playbook'
    args: ['-i', 'ansible/inventory.yml', 'ansible/playbook.yml']
