version: '3.1'

services:

  fix-api:
    image: nemdeveloping/fix-api:3.1
    restart: always
    depends_on:
      - fix-database
    networks:
      - fix-network
    ports:
      - 8080:8080
    environment:
      DB_USER: exampleuser
      DB_PASSWORD: examplepass
      DB_NAME: fix
      DB_HOSTNAME: fix-database


  fix-app:
    image: nemdeveloping/fix-app:2.0
    restart: always
    depends_on:
      - fix-database
      - fix-api
    networks:
      - fix-network
    ports:
      - 8000:5173
    environment:
      API_URL: "http://fix-api:8080"
      APP_URL: "http://localhost:8000"


  fix-database:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: fix
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - fix-network
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    networks:
      - fix-network
    ports:
      - 8082:8080
volumes:
  fix:
  db:


networks:
  fix-network:  
