version: '3.1'

services:

  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - fix-network

  fix-api:
    image: nemdeveloping/fix-api:3.5
    restart: always
    depends_on:
      - fix-database
    networks:
      - fix-network
    environment:
      DB_USER: exampleuser
      DB_PASSWORD: examplepass
      DB_NAME: fix
      DB_HOSTNAME: fix-database
    ports:
      - "8000:8080"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.fix-api.rule=PathPrefix(`/api`)"
    - "traefik.http.middlewares.api-stripprefix.stripPrefix.prefixes=/api"
    - "traefik.http.routers.fix-api.middlewares=api-stripprefix"
    - "traefik.http.services.fix-api.loadbalancer.server.port=8080"


  fix-app:
    image: nemdeveloping/fix-app:2.2
    restart: always
    depends_on:
      - fix-database
      - fix-api
    networks:
      - fix-network
    environment:
      API_URL: "http://fix-api:8080"
      APP_URL: "http://localhost:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fix-app.rule=PathPrefix(`/`)"
      - "traefik.http.services.fix-app.loadbalancer.server.port=5173"

  fix-database:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: fix
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - fix-network
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: fix-database
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: /phpmyadmin/
    networks:
      - fix-network
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.phpmyadmin.rule=PathPrefix(`/phpmyadmin`)"

    - "traefik.http.middlewares.phpmyadmin-stripprefix.stripPrefix.prefixes=/phpmyadmin"
    - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-stripprefix"

    - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

volumes:
  fix:
  db:

networks:
  fix-network:
